export const TEAM_COLORS: Record<string, string> = {
  coordinator: '#3B82F6',
  research_agent: '#6366F1',
  data_agent: '#10B981',
  analyzer_agent: '#F59E0B',
  modeler_agent: '#EC4899',
  algorithm_engineer_agent: '#8B5CF6',
  financial_analyst_agent: '#14B8A6',
  solver_agent: '#EF4444',
  writer_agent: '#06B6D4',
  peer_review_agent: '#F97316',
  experimentation_agent: '#A855F7',
  figure_agent: '#22D3EE',
  requirement_decomposer: '#84CC16',
  innovation_agent: '#E879F9',
  summary_agent: '#FB923C',
};

export const TEAM_LABELS: Record<string, string> = {
  coordinator: '协调者',
  research_agent: '研究员',
  data_agent: '数据分析师',
  analyzer_agent: '分析师',
  modeler_agent: '建模师',
  algorithm_engineer_agent: '算法工程师',
  financial_analyst_agent: '金融分析师',
  solver_agent: '求解器',
  writer_agent: '写作专家',
  peer_review_agent: '审稿人',
  experimentation_agent: '实验设计专家',
  figure_agent: '科研绘图师',
  requirement_decomposer: '需求分解器',
  innovation_agent: '创新发现专家',
  summary_agent: '总结专家',
  system: '系统',
  user: '你',
};

export const TEAM_ICONS: Record<string, string> = {
  coordinator: 'Users',
  research_agent: 'Search',
  data_agent: 'Database',
  analyzer_agent: 'BarChart3',
  modeler_agent: 'Box',
  algorithm_engineer_agent: 'Code2',
  financial_analyst_agent: 'TrendingUp',
  solver_agent: 'Cpu',
  writer_agent: 'PenTool',
  peer_review_agent: 'CheckCircle2',
  experimentation_agent: 'FlaskConical',
  figure_agent: 'Palette',
  requirement_decomposer: 'ListTodo',
  innovation_agent: 'Lightbulb',
  summary_agent: 'FileText',
};

export const TAB_META: Record<string, { title: string; subtitle: string }> = {
  dashboard: { title: '仪表盘', subtitle: '系统状态与快速开始' },
  generate: { title: '任务执行', subtitle: '实时监控 Agent 协作' },
  files: { title: '文件管理', subtitle: '数据文件与知识库' },
  pdf: { title: 'PDF 管理', subtitle: '论文解析与下载' },
  history: { title: '历史任务', subtitle: '任务记录与回溯' },
  agents: { title: 'Agent 管理', subtitle: '团队配置与模型路由' },
  workflows: { title: '工作流', subtitle: 'LangGraph 编排配置' },
  memory: { title: '记忆系统', subtitle: '经验教训与任务记忆' },
  environment: { title: '环境管理', subtitle: 'Conda / Venv 管理' },
  settings: { title: '系统设置', subtitle: 'Provider / MCP / 知识库' },
};